local HttpService = game:GetService("HttpService")
local RunService = game:GetService("RunService")
local Workspace = game:GetService("Workspace")

local BASE_URL = "http://127.0.0.1:8765"
local POLL_INTERVAL = 2

local function decodeJson(text)
	return HttpService:JSONDecode(text)
end

local function encodeJson(value)
	return HttpService:JSONEncode(value)
end

local function httpGet(path)
	local ok, response = pcall(function()
		return HttpService:GetAsync(BASE_URL .. path, false)
	end)

	if not ok then
		warn("[Bridge] GET failed:", response)
		return nil
	end

	return response
end

local function httpPost(path, payload)
	local ok, response = pcall(function()
		return HttpService:PostAsync(
			BASE_URL .. path,
			encodeJson(payload),
			Enum.HttpContentType.ApplicationJson,
			false
		)
	end)

	if not ok then
		warn("[Bridge] POST failed:", response)
		return nil
	end

	return response
end

local function splitPath(path)
	local result = {}

	for segment in string.gmatch(path, "[^/]+") do
		table.insert(result, segment)
	end

	return result
end

local function resolvePath(path)
	if path == "Workspace" then
		return Workspace
	end

	local current = game

	for _, segment in ipairs(splitPath(path)) do
		current = current:FindFirstChild(segment)
		if not current then
			return nil
		end
	end

	return current
end

local function ensureFolder(name, parentPath)
	local parent = resolvePath(parentPath or "Workspace")
	if not parent then
		return false, "parent_not_found"
	end

	local existing = parent:FindFirstChild(name)
	if existing and existing:IsA("Folder") then
		return true, "folder_exists"
	end

	local folder = Instance.new("Folder")
	folder.Name = name
	folder.Parent = parent
	return true, "folder_created"
end

local function toVector3(value, fallback)
	if typeof(value) == "table" and #value == 3 then
		return Vector3.new(value[1], value[2], value[3])
	end

	return fallback
end

local function toColor3(value, fallback)
	if typeof(value) == "table" and #value == 3 then
		return Color3.new(value[1], value[2], value[3])
	end

	return fallback
end

local function createPart(command)
	local parent = resolvePath(command.parent or "Workspace")
	if not parent then
		return false, "parent_not_found"
	end

	local part = Instance.new("Part")
	part.Name = command.name or "GeneratedPart"
	part.Size = toVector3(command.size, Vector3.new(4, 1, 4))
	part.Position = toVector3(command.position, Vector3.new(0, 5, 0))
	part.Anchored = command.anchored ~= false
	part.Color = toColor3(command.color, Color3.new(1, 1, 1))

	if command.shape == "Ball" then
		part.Shape = Enum.PartType.Ball
	elseif command.shape == "Cylinder" then
		part.Shape = Enum.PartType.Cylinder
	else
		part.Shape = Enum.PartType.Block
	end

	part.Parent = parent
	return true, "part_created"
end

local function setProperty(command)
	local target = resolvePath(command.target)
	if not target then
		return false, "target_not_found"
	end

	local propertyName = command.property
	local value = command.value

	local ok, err = pcall(function()
		target[propertyName] = value
	end)

	if not ok then
		return false, err
	end

	return true, "property_set"
end

local function createScript(command)
	local parent = resolvePath(command.parent or "ServerScriptService")
	if not parent then
		return false, "parent_not_found"
	end

	local scriptInstance
	if command.className == "LocalScript" then
		scriptInstance = Instance.new("LocalScript")
	else
		scriptInstance = Instance.new("Script")
	end

	scriptInstance.Name = command.name or "GeneratedScript"
	scriptInstance.Source = command.source or "-- generated by bridge"
	scriptInstance.Parent = parent
	return true, "script_created"
end

local handlers = {
	ensure_folder = function(command)
		return ensureFolder(command.name or "Generated", command.parent)
	end,
	create_part = createPart,
	set_property = setProperty,
	create_script = createScript,
}

local function executeCommand(command)
	local commandType = command.type
	local handler = handlers[commandType]

	if not handler then
		return {
			type = commandType,
			ok = false,
			message = "unknown_command",
		}
	end

	local ok, message = handler(command)
	return {
		type = commandType,
		ok = ok,
		message = message,
		name = command.name,
	}
end

local function collectWorkspaceState(results)
	local children = {}

	for _, child in ipairs(Workspace:GetChildren()) do
		table.insert(children, child.Name)
	end

	return {
		workspaceChildren = children,
		workspaceChildCount = #children,
		lastResults = results or {},
		serverTime = os.time(),
	}
end

local function heartbeat(results)
	httpPost("/state", collectWorkspaceState(results))
end

local accumulated = 0

RunService.Heartbeat:Connect(function(deltaTime)
	accumulated += deltaTime

	if accumulated < POLL_INTERVAL then
		return
	end

	accumulated = 0

	local body = httpGet("/commands")
	if not body then
		heartbeat({})
		return
	end

	local decoded = decodeJson(body)
	local commands = decoded.commands or {}
	local results = {}

	for _, command in ipairs(commands) do
		table.insert(results, executeCommand(command))
	end

	heartbeat(results)
end)
